# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/caculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainCaculator(object):
    def setupUi(self, MainCaculator):
        MainCaculator.setObjectName("MainCaculator")
        MainCaculator.resize(429, 334)
        self.centralwidget = QtWidgets.QWidget(MainCaculator)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(300, 120, 111, 41))
        self.btn_del.setObjectName("btn_del")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(20, 120, 261, 41))
        self.btn_clear.setObjectName("btn_clear")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 170, 411, 131))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_multi = QtWidgets.QPushButton(self.widget)
        self.btn_multi.setObjectName("btn_multi")
        self.gridLayout.addWidget(self.btn_multi, 0, 3, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.widget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 0, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.widget)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 1, 0, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.widget)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 2, 0, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 2, 3, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.widget)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 0, 2, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.widget)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 2, 2, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.widget)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 0, 1, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.widget)
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 3, 0, 1, 1)
        self.btn_sub = QtWidgets.QPushButton(self.widget)
        self.btn_sub.setObjectName("btn_sub")
        self.gridLayout.addWidget(self.btn_sub, 1, 3, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.widget)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 1, 2, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(self.widget)
        self.btn_divide.setObjectName("btn_divide")
        self.gridLayout.addWidget(self.btn_divide, 3, 2, 1, 1)
        self.btn_dot = QtWidgets.QPushButton(self.widget)
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout.addWidget(self.btn_dot, 3, 1, 1, 1)
        self.btn_equal = QtWidgets.QPushButton(self.widget)
        self.btn_equal.setObjectName("btn_equal")
        self.gridLayout.addWidget(self.btn_equal, 3, 3, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.widget)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 1, 1, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.widget)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 2, 1, 1, 1)
        self.line_result = QtWidgets.QLineEdit(self.centralwidget)
        self.line_result.setGeometry(QtCore.QRect(20, 10, 391, 101))
        self.line_result.setObjectName("line_result")
        MainCaculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainCaculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 429, 21))
        self.menubar.setObjectName("menubar")
        MainCaculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainCaculator)
        self.statusbar.setObjectName("statusbar")
        MainCaculator.setStatusBar(self.statusbar)

        self.retranslateUi(MainCaculator)
        QtCore.QMetaObject.connectSlotsByName(MainCaculator)

    def retranslateUi(self, MainCaculator):
        _translate = QtCore.QCoreApplication.translate
        MainCaculator.setWindowTitle(_translate("MainCaculator", "MainWindow"))
        self.btn_del.setText(_translate("MainCaculator", "Del"))
        self.btn_clear.setText(_translate("MainCaculator", "Clear"))
        self.btn_multi.setText(_translate("MainCaculator", "*"))
        self.btn1.setText(_translate("MainCaculator", "1"))
        self.btn4.setText(_translate("MainCaculator", "4"))
        self.btn7.setText(_translate("MainCaculator", "7"))
        self.btn_add.setText(_translate("MainCaculator", "+"))
        self.btn3.setText(_translate("MainCaculator", "3"))
        self.btn9.setText(_translate("MainCaculator", "9"))
        self.btn2.setText(_translate("MainCaculator", "2"))
        self.btn0.setText(_translate("MainCaculator", "0"))
        self.btn_sub.setText(_translate("MainCaculator", "-"))
        self.btn6.setText(_translate("MainCaculator", "6"))
        self.btn_divide.setText(_translate("MainCaculator", "/"))
        self.btn_dot.setText(_translate("MainCaculator", "."))
        self.btn_equal.setText(_translate("MainCaculator", "="))
        self.btn5.setText(_translate("MainCaculator", "5"))
        self.btn8.setText(_translate("MainCaculator", "8"))
        self.line_result.setInputMask(_translate("MainCaculator", "0"))

