# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_34 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_34.setObjectName("btn_34")
        self.gridLayout.addWidget(self.btn_34, 2, 3, 1, 1)
        self.btn_41 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_41.setObjectName("btn_41")
        self.gridLayout.addWidget(self.btn_41, 3, 0, 1, 1)
        self.btn_33 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_33.setObjectName("btn_33")
        self.gridLayout.addWidget(self.btn_33, 2, 2, 1, 1)
        self.btn_14 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_14.setObjectName("btn_14")
        self.gridLayout.addWidget(self.btn_14, 0, 3, 1, 1)
        self.btn_12 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_12.setObjectName("btn_12")
        self.gridLayout.addWidget(self.btn_12, 0, 1, 1, 1)
        self.btn_21 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_21.setObjectName("btn_21")
        self.gridLayout.addWidget(self.btn_21, 1, 0, 1, 1)
        self.btn_11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_11.setObjectName("btn_11")
        self.gridLayout.addWidget(self.btn_11, 0, 0, 1, 1)
        self.btn_13 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_13.setObjectName("btn_13")
        self.gridLayout.addWidget(self.btn_13, 0, 2, 1, 1)
        self.btn_22 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_22.setObjectName("btn_22")
        self.gridLayout.addWidget(self.btn_22, 1, 1, 1, 1)
        self.btn_23 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_23.setObjectName("btn_23")
        self.gridLayout.addWidget(self.btn_23, 1, 2, 1, 1)
        self.btn_24 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_24.setObjectName("btn_24")
        self.gridLayout.addWidget(self.btn_24, 1, 3, 1, 1)
        self.btn_31 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_31.setObjectName("btn_31")
        self.gridLayout.addWidget(self.btn_31, 2, 0, 1, 1)
        self.btn_32 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_32.setObjectName("btn_32")
        self.gridLayout.addWidget(self.btn_32, 2, 1, 1, 1)
        self.btn_44 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_44.setObjectName("btn_44")
        self.gridLayout.addWidget(self.btn_44, 3, 3, 1, 1)
        self.btn_42 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_42.setObjectName("btn_42")
        self.gridLayout.addWidget(self.btn_42, 3, 1, 1, 1)
        self.btn_43 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_43.setObjectName("btn_43")
        self.gridLayout.addWidget(self.btn_43, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_34.setText(_translate("MainWindow", "PushButton"))
        self.btn_41.setText(_translate("MainWindow", "PushButton"))
        self.btn_33.setText(_translate("MainWindow", "PushButton"))
        self.btn_14.setText(_translate("MainWindow", "PushButton"))
        self.btn_12.setText(_translate("MainWindow", "PushButton"))
        self.btn_21.setText(_translate("MainWindow", "PushButton"))
        self.btn_11.setText(_translate("MainWindow", "Caculator"))
        self.btn_13.setText(_translate("MainWindow", "PushButton"))
        self.btn_22.setText(_translate("MainWindow", "PushButton"))
        self.btn_23.setText(_translate("MainWindow", "PushButton"))
        self.btn_24.setText(_translate("MainWindow", "PushButton"))
        self.btn_31.setText(_translate("MainWindow", "PushButton"))
        self.btn_32.setText(_translate("MainWindow", "PushButton"))
        self.btn_44.setText(_translate("MainWindow", "PushButton"))
        self.btn_42.setText(_translate("MainWindow", "PushButton"))
        self.btn_43.setText(_translate("MainWindow", "PushButton"))

